repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [ --py313-plus ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: [ "--fix", "--line-length=120" ]

  - repo: https://foundry.fsky.io/vel/ty-pre-commit
    rev: 0.0.3
    hooks:
      - id: ty-check
        additional_dependencies:
          - aiogram
          - alembic
          - asyncpg
          - pydantic
          - pydantic-settings
          - redis
          - sqlalchemy[asyncio]
